[package]
name = "libp2p-fix"
version = "0.1.0"
edition = "2021"

[dependencies]
libp2p-tcp = { version = "0.42.0", features = ["tokio"] }
libp2p-identity = { version = "=0.2.9", features = ["peerid", "ed25519"] }





